### ISSUE TITLE
Option not recognized

### ISSUE THREAD

**Issue by pablovilas** [edvin/fxldemo-gradle#1]
Hi, running the gradle example with task "installer" said that  "identifier" option is not recognized. I just removed the option
`"-identifier", "${rootProject.group}.${appFilename}"` and works. There is another option `-Bidentifier` that do the trick.
Thanks.

**Comment by edvin** [comment]
Thank you :) The typo has been fixed, and the version is bumped to 10.0.11, which now finally supports Gradle :)

**Comment by pablovilas** [comment]
Thanks!!!
