### ISSUE TITLE
build.gradle - version 1.0.20 does not exist

### ISSUE THREAD

**Issue by jafhueppe** [edvin/fxldemo-gradle#11]
Hey there,

I was looking in your build.gradle file for comparison with my file.
I tried to use 
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'no.tornado:fxlauncher-gradle-plugin:1.0.20'
    }
}
```
but I got the error, that there is no version 1.0.20. 

Did you forget to upload it to the maven repo or is it a typo in this build.gradle file?

Thank you very much

Best regards

**Comment by edvin** [comment]
Sorry about that, just released 1.0.20 :) It should hit Maven Central any minute now :)

**Comment by jafhueppe** [comment]
Thank you!

**Comment by edvin** [comment]
Thanks for reporting :) I don't use Gradle myself so this slipped under the radar :)
