### ISSUE TITLE
SCP not available for Windows?

### ISSUE THREAD

**Issue by Mosch0512** [edvin/fxldemo-gradle#16]
As of my research scp is not available on windows only pscp?

![image](https://user-images.githubusercontent.com/48485443/54269635-b6c72100-45a3-11e9-9f7b-2f38095d2070.png)

![image](https://user-images.githubusercontent.com/48485443/54269878-37861d00-45a4-11e9-9785-6fb3a114dc19.png)

**Comment by edvin** [comment]
pscp doesn't come with Windows either. If you need scp, simply install it :)
