### ISSUE TITLE
Deploy to Amazon S3 example

### ISSUE THREAD

**Issue by pablovilas** [edvin/fxldemo-gradle#2]
Hello Edvin,

I've an example of build.gradle that deploys to Amazon S3 if you are interested to add it to your examples.

**Comment by edvin** [comment]
Absolutely :) Thanks a lot!

**Comment by pablovilas** [comment]
Here is a public Gist:
https://gist.github.com/pablovilas/ac5f037990eb1686c08d4f659792d11a
Thanks to you.

**Comment by edvin** [comment]
Since we now have a Gradle plugin, I added information about deployment to Amazon S3 to the README file of the project. It might be possible to include this as an option for the plugin in the future. Thanks a lot for contributing this!
