### ISSUE TITLE
How to troubleshoot launch problems?

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxldemo-gradle#3]
I used your gradle example to add fx-launcher to my project. Building the .msi installer works fine and it installs. But when it runs, I get a ClassNotFoundException listing my main application class. I've triple-checked that I have the fully-qualified classname correct. 

I manually deployed, by copying all the files from the build/fxlauncher folder to my application URL. So, for example,
applicationUrl = https://myapp.s3.amazonaws.com/releases/myapp/
lib first.jar is at https://myapp.s3.amazonaws.com/releases/myapp/first.jar, etc.

I can't tell where the launcher is downloading the files to, so I don't know how to verify that it was able to pull down all the jars correctly. Any ideas on what I should be looking at?

TIA!
Chris

**Comment by ChrisLMerrill** [comment]
I should add: when I run the fxlauncher.jar in build/fxlauncher, the updating progress bar shows for a moment and then my app starts.

**Comment by edvin** [comment]
If you used the installer and didn't specify the cache dir (https://github.com/edvin/fxlauncher/wiki/Optional-Cache-Directory) the downloaded artifacts will be placed in the current working directory. You could try to open a shell, cd into the folder where the app is installed (where you have fxlauncher.jar) and run `java -jar fxlauncher.jar` from there. If the app fails to start it should give you a stack trace and you should be able to see what files where downloaded and which weren't. Please check the files against `app.xml` to see if there are any discrepancies. Are you using basic auth? This is a new feature, so you might try without to see if your issue is with authentication somehow.

Hope this helps. If not - would it be possible for me to try the app directly?

**Comment by ChrisLMerrill** [comment]
I found the installation folder and none of my jars are in the installation folder (either the root or the app folder. I ran from the command-line and got the error below. From which I guessed that the app needs Administrator permissions to modify it's installation folder on Windows. So I ran it as Administrator and it worked - all jars downloaded and the app runs.

So I'm guessing I need to use the cacheDir parameter in my gradle build file to have the launcher download the app into a user folder. I'll look into that. 

Thanks for the help!

[chris.SilverSurfer] ➤ java -jar fxlauncher.jar
Nov 24, 2016 9:25:06 AM fxlauncher.Launcher lambda$start$0
INFO: Using cache dir .
Nov 24, 2016 9:25:06 AM fxlauncher.Launcher lambda$start$0
WARNING: Error during File Synchronization phase
java.nio.file.AccessDeniedException: C:\Program Files\museide\app\.\airline.jar
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at fxlauncher.Launcher.syncFiles(Launcher.java:160)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:78)
        at java.lang.Thread.run(Thread.java:745)

**Comment by edvin** [comment]
That sounds about right :) You can use the `USERLIB` special keyword in the cache-dir parameter to find a suitable folder based on the os:

`--cache-dir=USERLIB/MyApp` 

Let me know how it goes!

**Comment by ChrisLMerrill** [comment]
I solved this by adding this to my Gradle config:

    cacheDir 'USERLIB/MyApp'

This raises the question: why did the demo work for me?  I didn't run the demo as an admin...and the demo build.gradle does not specify the cacheDir.

I have Wix installed (was trying out FibreFoX/javafx-gradle-plugin as well) and so I got a .msi installer, rather than a .exe installer. Would that explain the difference?

**Comment by edvin** [comment]
That would explain it indeed. According to the JavaPackager docs, the default installation path for MSI is %ProgramFiles% while it is %LOCALAPPDATA% for EXE :)

https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

I'll make sure to mention this in the README. Thanks again for getting back to me.
