### ISSUE TITLE
gradle example deployS3 target

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxldemo-gradle#4]
When I run 'gradle deployS3' using the config in the readme, I get this:

> Could not find property 'appDeployTarget' on task ':deployS3'.

task deployS3(type: Exec) {
    // You need to have installed AWS command line interface: https://aws.amazon.com/cli/
    commandLine 'aws', 'configure', 'set', 'aws_access_key_id', '******'
    commandLine 'aws', 'configure', 'set', 'aws_secret_access_key', '*******'
    commandLine 'aws', 's3', 'cp', 'releases/ide2', appDeployTarget, '--acl', 'public-read', '--recursive', '--region', 'us-east-1'
}

Not sure exactly what it is looking for. Any suggestion?

**Comment by edvin** [comment]
The error message simply says that you haven't defined that variable. You need to define appDeployTarget as the host/path to your s3 instance I guess :) I've never used s3 myself, but somebody contributed the s3 example. Check the documentation for the aws command and see what parameter 4 is and define that in a variable called appDeployTarget :)

**Comment by ChrisLMerrill** [comment]
`So` I decided to take another approach, because the solution in the readme:
1) required the user to have AWS command-line tools installed
2) has the AWS credentials in the build file    :o

Instead, I used the gradle-aws-plugin (https://github.com/classmethod/gradle-aws-plugin) and this in my build.gradle file:

`buildscript
    {
    repositories
        {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }          // for gradle-aws-plugin
        }
    dependencies
        {
        classpath 'no.tornado:fxlauncher-gradle-plugin:1.0.14'  // auto-update and native installers
        classpath "jp.classmethod.aws:gradle-aws-plugin:0.30"   // deploy to S3
        }
    }

apply plugin: 'jp.classmethod.aws.s3'
task syncToS3(type: jp.classmethod.aws.gradle.s3.SyncTask) {
    bucketName 'bucketname/path/to/files'
    source file('build/fxlauncher')
    }`

This page describes how to specify your AWS credentials 
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
You can provide them in a $HOME/.aws/credentials file, environment variables or java system properties, so it should fit well into any Java build process.

This works much better for minimizing the build requirements and keeping credentials secure. It was easier, too...at least for me.    :)

**Comment by edvin** [comment]
That's much cleaner. Thanks for letting us know :)
