### ISSUE TITLE
What does deployTarget do in the build.gradle file?

### ISSUE THREAD

**Issue by gcstang** [edvin/fxldemo-gradle#5]
I see this in the build.gradle file but I'm not sure what to replace this with for my own project.

`deployTarget 'w48839@fxldemo.tornado.no:fxldemo'`

**Comment by gcstang** [comment]
please disregard

**Comment by ghost** [comment]
I have same question what does it mean?

**Comment by edvin** [comment]
It's used to transfer the application using scp to the target (username@hostname:path) you specify.
