### ISSUE TITLE
Proper Gradle Task Order?

### ISSUE THREAD

**Issue by gcstang** [edvin/fxldemo-gradle#6]
Is there a document on what the proper order is to run these gradle tasks?

1. copyAppDependencies 
2. deployApp
3. embedApplicationManifest
4. generateApplicationManifest
5. generateNativeInstaller

Here is what I'm hoping this will allow me to do:

1. Build my project
2. Create Native version
3. Deploy the native versions to users
4. Auto update the version that the users have without having to send them a new version.

I also ran into an issue running the deployApp on my Mac it fails with a -1 status on the scp.
Instead I ran this manually and it seemed to work for me, but I don't see any native applications:
`scp -r build/fxlauncher/. myuser@myserver.home.com:fxldemo`

Thank you for your help.

**Comment by edvin** [comment]
The tasks have dependencies on each other, so you can just run the one you want, and it will call the others first. So to generate a native installer, just call `generateNativeInstaller`.

You'd typically only do this once, and then later you just run `deployApp` to push a new version.

The installer should be built into `build/installer/bundles/app-name`. If it's not there after running `generateNativeInstaller` you should have an error message in your console hinting to the problem.

Does this help? If not, can you post your app somewhere so I can take a look?

**Comment by gcstang** [comment]
Ok, I do now see the native installer is created(it's rather large compared to creating it directly which is only about 5MB, this one is 63MB).  Do I push this out to the server for upgrades?  Does the native version auto update also or just the jar based one that is pushed out with deployApp ?

Also thank you for your quick response!

**Comment by edvin** [comment]
No problem :) The native version never updates, as it is really just a shell for starting fxlauncher. There is only a need to update the native installer if you change the fxlauncher version or change the installer icons etc. We currently have no support for updating the installed .exe, but we're going to address this in version 2.0.

**Comment by gcstang** [comment]
Ok so the native version is just like running the fxlauncher with a url so it downloads and runs the latest version all the time based on the latest on the deployedApp target?  If correct I wouldn't need to update the exe, dmg, etc... since it would just get the latest from the server.

Any reason the native version is so large compared to the native one I built with the standard javafx native build tools?  (Disregard I see it's packaging the JRE in the Mac Native version, I'll have to see if there is a way to stop that.)

**Comment by edvin** [comment]
That's correct. `javapackager` includes the JRE in the generated installer on all platforms. You can of course just distribute the launcher itself, but that defeats the purpose of being able to distribute a fully self contained application. FXLauncher doesn't augment the generated installer in any way so it would be the exact same size as running `javapackager` manually.

**Comment by gcstang** [comment]
Ok, thank you for your help.

In regards to the scp functionality I found your plugin source and added the -v parameter to it and it helped me to figure out the deployApp and get it working.  Maybe it can be an option to pass in some other scp parameters or just a true/false option to turn verbose on when running the deployApp task?

**Comment by edvin** [comment]
That sounds like a good idea. Preferably we'd use an ssh/scp library so we don't need to depend on any locally installed software as well, but we could for sure add `scpOptions` or something similar for now.

I'll add this for the 1.0.15 release. I think we'll do that release some time next week.

**Comment by edvin** [comment]
I just added the `scpOptions` parameter :)

**Comment by gcstang** [comment]
Thank you, I have the native one running but the "Updating..." dialog never goes away but the application is running.

UPDATE:

Oddly enough it seems to go away if I open a screen of my application that lays over the top of it.

**Comment by edvin** [comment]
The updating stage is listening for the primaryStage to open, so it won't go away until you actually show the primary stage passed to your app. If you don't want to show something right away you should be able to just show and immediately hide the primary stage. Let me know if that doesn't work for you.

We can add an option to close the updating dialog once the update is complete and your app starts to launch. Actually I think this might be a good default as well. I'll look into this for 1.0.15.

**Comment by gcstang** [comment]
I like the idea of closing it once it's complete as a default.

**Comment by edvin** [comment]
Great. We'll discuss if this should be the default or if we should just add an option for it. Let's leave this issue open until it's implemented :)

**Comment by edvin** [comment]
FXLauncher 1.0.15 has been released with this new behavior as default. If you want to keep the update screen around until the primary stage is shown you must now specify `lingeringUpdateScreen=true`.
