### ISSUE TITLE
Tornadofx App with FXLauncher: ClassNotFoundError

### ISSUE THREAD

**Issue by niteesh19** [edvin/fxldemo-gradle#7]
I am trying to deploy a simple tornadofx app with FXLauncher but sadly I am running into this basic issue.
Below is the OnixGUI.kt:

`package app`
`import javafx.stage.Stage`
`import tornadofx.App`
`import view.MyView`
`class OnixGUI : App() {`
`    override val primaryView = MyView::class`
`    override fun start(stage: Stage) {`
`        super.start(stage)`
`    }`
`}`

and build.gradle : 

`group 'com.abc.onix'`
`version '0.0.1-SNAPSHOT'`
`buildscript {`
`    ext.kotlin_version = '1.1.1'`
`    repositories {`
`        mavenCentral()`
`    }`
`    dependencies {`
`        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"`
`        classpath 'no.tornado:fxlauncher-gradle-plugin:1.0.16'`
`    }`
`}`
`apply plugin: 'kotlin'`
`apply plugin: 'maven-publish'`
`apply plugin: 'idea'`
`apply plugin: 'no.tornado.fxlauncher'`
`apply plugin: 'application'`
`sourceCompatibility = 1.8`
`mainClassName = 'app.OnixGUI'`
`fxlauncher {`
`    applicationVendor 'Abc'`
`    applicationUrl 'https://learning1.000webhostapp.com/'`
`    applicationMainClass 'app.OnixGUI'`
`}`
`compileKotlin {`
    `kotlinOptions.jvmTarget= "1.8"`
`}`
`repositories {`
    `mavenCentral()`
    `mavenLocal()`
    `jcenter()`
`}`
`dependencies {`
    `compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"`
    `compile 'no.tornado:tornadofx:1.7.4'`
`}` 

Error during create application phase:
`java.lang.ClassNotFoundException: app.OnixGUI`

I tried testing the app locally as well as on deploy but I get the same error. For dev purpose, I do not need the deployApp param, hence not shown here.

This error comes only when I double click the fxlauncher.jar, But when I run it using the command 
`java -jar  fxlauncher.jar` it works fine.
Also I downloaded the sample fxldemo-gradle and its fxlauncher.jar runs fine even on double clicking.

What am I missing?

**Comment by edvin** [comment]
Could it be that you're running it in a folder where you don't have write permissions or something? If possible, could you upload the jar?

**Comment by niteesh19** [comment]
I have write permissions on the build folder.
PFA the zipped jar

[FXL.zip](https://github.com/edvin/fxldemo-gradle/files/1015170/FXL.zip)

**Comment by niteesh19** [comment]
Attaching the complete build folder. You can Ignore the previous zip.
[build.zip](https://github.com/edvin/fxldemo-gradle/files/1015215/build.zip)

**Comment by niteesh19** [comment]
@edvin any update?

**Comment by edvin** [comment]
Sorry about the delay, I've had to prioritize features in TornadoFX. I will look at it tomorrow and get back to you :)

**Comment by niteesh19** [comment]
No problem :)

**Comment by edvin** [comment]
Everything seems to be in order, and I can confirm that I can run fxlauncher.jar both by double clicking it and also via `java -jar fxlauncher.jar`.

Perhaps you have an old jre installed in your system, and this jre is used when you double click a jar?

**Comment by niteesh19** [comment]
I have the latest jre version... I actually uninstalled and installed again oracle jdk 8.
I shared this zip with 2 of my colleagues just for testing. One uses a windows 10 machine and at his end he was able to execute the jar successfully. The other one uses an ubuntu 14.04 machine and he gets the same error as I get. 
I am also using ubuntu 14.04.
I suspect this could be the issue. But still cant figure out a solution. 
I also tried giving executable permissions to the fxlauncher.jar but still it gives the same error.

It could also be possible that this error happens on our specific machines as me and my colleague (who uses ubuntu) machine have same set of libraries/packages installed.

**Comment by edvin** [comment]
Does it work with any other executable jar file on your Ubuntu 14.04?

**Comment by niteesh19** [comment]
Yea so the jar I downloaded from the demo fxlauncher page, that works.

Let me test it on a completely new Ubuntu 14.04

**Comment by niteesh19** [comment]
Just tested on a different ubuntu 14.04, Still facing the same issue.

**Comment by niteesh19** [comment]
Hey, I created a different app and deployed it on a cloud server and then tested it, and it was working flawlessly on my ubuntu machine.
Before I was not deploying the app but just using the embedApplicationManifest. 
Anyways, I am closing this issue. Thanks for your help.

**Comment by edvin** [comment]
Thanks for getting back to me, and sorry for the late response. Been swamped with TornadoFX lately.
