### ISSUE TITLE
SSLConnectionSocketFactory - Custom TrustManager for validating cert digest

### ISSUE THREAD

**Issue by niteesh19** [edvin/fxldemo-gradle#8]
Can we implement a custom TrustManager? basically implementing TrustStrategy isTrusted() method to validate the cert digest of the server where fxlauncher.jar is deployed.

We could have a parameter named "--cert-digest='qwertyuiopasdfghjklzxcvbnm'" which would be used for validating the server's certdigest.

This could be an alternative to the current implementation of AbstractLauncher -> setupIgnoreSSLCertificate

**Comment by edvin** [comment]
That sounds like a very good idea. Do you want to give it a go? My schedule is tightly packed at the moment :)

**Comment by niteesh19** [comment]
Well I haven't really tried implementing this before; was just looking around online to get some hints on this. 
Let me do some more research and then I can probably contribute.

**Comment by edvin** [comment]
That sounds great! Thank you so far :)

**Comment by niteesh19** [comment]
Hi @edvin 
Please review the following pull requests : 
https://github.com/edvin/fxlauncher/pull/76
https://github.com/edvin/fxlauncher-gradle-plugin/pull/3

Couple of concerns:

I have added a new dependency of httpclient v4.5.2 because of which in the pom.xml I had to add maven-assembly-plugin which creates an executable jar with this string appended at the last of the jar name "-jar-with-dependencies". So the maven now basically installs two jars; one fxlauncher-1.0.17-SNAPSHOT.jar and one fxlauncher-1.0.17-SNAPSHOT-jar-with-dependencies.jar. The second jar needs to be referenced by the project fxlauncher-gradle-plugin.
I wanted to add a HttpsURLConnection.setDefaultHostnameVerifier() which basically would verify the hostname of the connecting url and the hostname from the "applicationUrl" specified in the gradle build. But I was not able to do it as the HostnameVerifier gets ignored (don't know why.) Should this be present ? Please let me know if you have a way of implementing this. Even if not implemented, this works fine.

**Comment by niteesh19** [comment]
Hi @edvin . Can you please review the above changes and let me know if any modification is required ?
